name: github pages

on:
  push:
    branches:
      - source  # Set a branch to deploy

jobs:
    render:
    	name: Build site
    	runs-on: macOS-latest
    	env:
      	GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    	steps:
      	- name: Checkout repo
        	uses: actions/checkout@v2
        	with:
          	submodules: recursive
        

        - name: Setup pandoc
        	uses: r-lib/actions/setup-pandoc@v1
        	with:
          	pandoc-version: '2.12'

        - name: Setup Hugo
        	uses: peaceiris/actions-hugo@v2
        	with:
          	hugo-version: 'latest'
          	extended: true
      	- name: Build site
        	run: hugo 
      	- name: Deploy
        	uses: peaceiris/actions-gh-pages@v3
        	with:
          	github_token: ${{ secrets.ACTIONS_TOKEN }}
          	publish_dir: ./public
          	publish_branch: main
          	cname: https://anthony-tan.com

