# .github/workflows/main.yml
name: Publish Site

on:
  push:
    branches: 
      - source
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.ACTIONS_TOKEN }}
          branch: main
          hugoVersion: 'extended_'
          cname: https://anthony-tan.com
          repo: Tony-Tan.github.io
